### ISSUE TITLE
Examples generated incorrectly (`@example [object Object]`)

### ISSUE THREAD

**Issue by moltar** [fabien0102/openapi-codegen#36]
It looks like object examples get stringified incorrectly.

![screenshot-20220222T200832-S6SdWKun](https://user-images.githubusercontent.com/491247/155138667-7948f691-ce5a-474e-a970-cbe8c2d8aed0.png)

**Comment by fabien0102** [comment]
🤔 I'm a bit surprise for this one since I have a unit test about it…

https://github.com/fabien0102/openapi-codegen/blob/2105e99f03fe71251cf347e905c88cae9b4a39a1/plugins/typescript/src/core/schemaToTypeAliasDeclaration.test.ts#L771

Do you have an openapi example for repro?

(anyway, I was a bit lazy, I can probably improve the formatting, but still, this should not be `[object Object]`)
