### ISSUE TITLE
feature: option to generate indexes?

### ISSUE THREAD

**Issue by moltar** [fabien0102/openapi-codegen#37]
Right now the files are put in the `outputDir`, but no `index.ts` is created.

Should there be an option to just export everything from the index?

**Comment by fabien0102** [comment]
Since you can easily create the `index.ts` and it's a one time operation, I would prefer not.

I tend to use the `index.ts` to add some custom logic as injecting the react-query keys so regen this file will be annoying. And if a user don't like the barel pattern (so no `index.ts` for re-exporting) this will also be annoying.

With this in mind, I see more noises than real value for this option, so let keep it simple!
