### ISSUE TITLE
Syntax error generating types when example includes `*/`

### ISSUE THREAD

**Issue by atrakh** [fabien0102/openapi-codegen#57]
Hi, I've discovered a syntax error when attempting to generate types for an openapi spec containing "*/" in one of my examples.

The `openapi.json` contains a `components.schema` declaration (roughly) as follows:
```
      "CronTimingCreate": {
        "title": "CronTimingCreate",
        "required": [
          "type",
          "cron_expression"
        ],
        "type": "object",
        "properties": {
          "cron_expression": {
            "title": "Cron Expression",
            "type": "string",
            "description": "The string representing the timing's cron expression.",
            "format": "cron-string",
            "example": "*/5 * * * *"
          },
        },
        "additionalProperties": false,
        "description": "Cron timing schema for create requests."
      }
```

The issue seems to be stemming from the `example`, which contains `*/` -- which I believe is being detected as the end of the comment here: https://github.com/fabien0102/openapi-codegen/blob/2105e99f03fe71251cf347e905c88cae9b4a39a1/plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts#L614-L615

Ultimately, I get this output from `npx openapi-codegen gen api`:
```
Syntax Error: Unexpected token (468:8)
  466 |      * @format cron-string
  467 |      * @example 5 * * * *
> 468 |      */*/
      |        ^
  469 |     cron_expression: string;
  470 |     /*
  471 |      * The IANA time zone to use convert `time` in this timing.
  466 |      * @format cron-string
  467 |      * @example 5 * * * *
> 468 |      */*/
      |        ^
  469 |     cron_expression: string;
  470 |     /*
  471 |      * The IANA time zone to use convert `time` in this timing.
```

**Comment by fabien0102** [comment]
Amazing catch and bug description! This should be straight forward to fix (I hope 😅)

**Comment by fabien0102** [comment]
@atrakh  Quick question, I can't include any `*/` as is in a JSDoc comment (https://github.com/microsoft/tsdoc/issues/166)

So I have multiple choices:
- I can escape with a back slash (but I don't really like this since this is really misleading)
![image](https://user-images.githubusercontent.com/1761469/164213023-39c84312-0a01-4215-975c-9f92c52a64ef.png)
- I can skip totally the `@example` from the output (but you don't really know that an example exists…)
- I can replace the value with a placeholder
![image](https://user-images.githubusercontent.com/1761469/164212599-e95091f0-2375-40db-958d-e36af5893c0a.png)

Quickly thinking, I do prefer the last option since this is still giving some hint even if it's not perfect. Any opinion about this? Maybe a better copy? 🤔

**Comment by atrakh** [comment]
@fabien0102 the third option sounds the most reasonable to me. For context, I don’t personally care too much about the example being gone since my codegen api will be for internal use.

One small enhancement could be to include an  ‘@link’ to the original openapi spec, but that’s definitely a nit and likely not worth your time right now

Cheers and thanks for building this!
